### ISSUE TITLE
Found 'circle' as layer type but only 'symbol' is supported

### ISSUE THREAD

**Issue by distantnative** [nazka/mapbox-gl-js-spiderfy#20]
Is there any chance to support also simple circle layers?

Thanks a lot for your work!

**Comment by simondriesen** [comment]
This is not possible as the spiderfied markers use [`icon-offset`](https://docs.mapbox.com/style-spec/reference/layers/#layout-symbol-icon-offset) to position the markers around the cluster. This is no such thing as `circle-offset` for a circle layer sadly. 

You could try to use an icon layer with an sdf image that look like circles instead, like in [the demo](https://codepen.io/nazka-mapps/pen/KKXjJYX).

With `renderMethod` option "3D" it could be supported in the future as the markers around the cluster are positioned with coordinates instead of `icon-offset`. This method isn't perfect either though, especially if you start rotating the map.
